services:
  - type: web
    name: pdf-epub-converter-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: ./build.sh
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true 